# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       hawaii-wallpapers

# >> macros
# << macros

Summary:    Wallpapers for the Hawaii desktop environment
Version:    0.2.0
Release:    1
Group:      Applications/Multimedia
License:    CC-BY-SA, CC-BY, CC0
URL:        https://github.com/mauios/hawaii-wallpapers.git
Source0:    %{name}-%{version}.tar.bz2
Source100:  hawaii-wallpapers.yaml
BuildRequires:  cmake

%description
Collection of wallpapers shipped with the Hawaii desktop environment.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cd upstream
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd upstream
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/backgrounds/hawaii/16.jpg
%{_datadir}/backgrounds/hawaii/3.jpg
%{_datadir}/backgrounds/hawaii/Also_Calm.png
%{_datadir}/backgrounds/hawaii/Arancio.jpg
%{_datadir}/backgrounds/hawaii/Crane_Beach.jpg
%{_datadir}/backgrounds/hawaii/Grass.jpg
%{_datadir}/backgrounds/hawaii/Halfway_Gone.jpg
%{_datadir}/backgrounds/hawaii/Hawaii-blue.jpg
%{_datadir}/backgrounds/hawaii/Lighthouse_Cork.jpg
%{_datadir}/backgrounds/hawaii/Springlight.jpg
# >> files
# << files
