# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       wallpapers

# >> macros
# << macros

Summary:    wallpaper modules
Version:    0.2.0.20130714.a0a3db7
Release:    1
Group:      Applications/System
License:    BSD
Source0:    wallpapers-%{version}.tar.bz2
Source100:  wallpapers.yaml
BuildRequires:  cmake
BuildRequires:  python

%description
Wallpaper function modules


%prep
%setup -q -n %{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_INSTALL_PREFIX=/usr
    
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_datadir}/backgrounds/hawaii/16.jpg
%{_datadir}/backgrounds/hawaii/3.jpg
%{_datadir}/backgrounds/hawaii/Coasto.jpg
%{_datadir}/backgrounds/hawaii/Colorful*City.jpg
%{_datadir}/backgrounds/hawaii/Everest.jpg
%{_datadir}/backgrounds/hawaii/Halfway*Gone.jpg
%{_datadir}/backgrounds/hawaii/One*Path.jpg
%{_datadir}/backgrounds/hawaii/Springlight.jpg
%{_datadir}/backgrounds/hawaii/Also*Calm.png
# >> files
# << files
