# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       hawaii-wallpapers

# >> macros
# << macros

Summary:    Wallpapers for the Hawaii desktop environment
Version:    0.2.1
Release:    1
Group:      System/GUI/Other
License:    CC-BY-SA, CC-BY, CC0
BuildArch:  noarch
URL:        https://github.com/mauios/hawaii-wallpapers.git
Source0:    %{name}-%{version}.tar.xz
Source100:  hawaii-wallpapers.yaml
BuildRequires:  cmake

%description
Collection of wallpapers shipped with the Hawaii desktop environment.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cd upstream
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd upstream
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/backgrounds/hawaii/
# >> files
# << files
